### ISSUE TITLE
No Movie posters dyplay in movies, but posters display in tv shows. Is this just me? Or is this a Specto Fork issue? Will it be fixed on the next update? 

### ISSUE THREAD

**Issue by richd29** [mrknow/filmkodi#882]
## Please follow the guide below 
- Put an "x" into all boxes [ ] relevant to your *issue*
- Use *Preview* tab to see how your issue will actually look like
---
## Kodi & Addon 
- Kodi verison: _____
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ x] Specto
- [ ] FanFILM
- Version / Wersja: _____
---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

## Donation / Darowizna
This addons are free, but you can always thank the author for ... / Te wtyczki są darmowe, ale zawsze możesz podziękować autorowi za jej stworzenie...

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=HEV6TJY83S3Q4&lc=PL&item_name=Donation-Darowizna&currency_code=PLN&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted)

**Comment by BankruptEd** [comment]
Same here. It's the same in Exodus.

**Comment by richd29** [comment]
My Exodus is fine. It's just in specto in the movie section that's not populating the posters.

**Comment by BankruptEd** [comment]
Ya, Exodus seems fine for me now, but when I first noticed this, both were
involved. Just Specto now.

**Comment by dose420** [comment]
Same issue for about a week here. Movie covers dont load but tv covers do.

Kodi 17.2
Latest specto. Even did fresh install and nothing.

**Comment by Jackel278** [comment]
I have been having the same issue as well with the new versions of Kodi (17.2 and 17.3).  Completed uninstalls of the previous version of Kodi 17.1 on an iPad Air and Amazon Firestick (2nd generation) and completed a fresh install of Kodi 17.2 and Specto at first.  Specto art would not load in the movies section.  Completed uninstall of Kodi 17.2 and fresh install of Kodi 17.3 and Specto.  Same issue.  For me the problem is confined only to Specto as I am not having any issue with Exodus.  As someone else commented it is strange however that the posters appear in the TV Shows section of Specto but not the movie section.  Hopefully it should be a quick fix and resolved in the next couple of weeks.

**Comment by jlasby3131** [comment]
I have the same problem with specto only. I have three android boxes all have the same issue. Just updated to 17.3 on all three with clean installs. Wierd works fine on my phone.  The only thing I have not tried is a factory reset. I read some where else this helped. Makes me think it will becuse I recently had to wipe my phone.

**Comment by jlasby3131** [comment]
Just did a factory reset on one of the boxes and installed kodi 17.3 fusion to have the auto config wizard and then installed specto. Still the same problem. Exodus and SALTS work fine

**Comment by reignmyway** [comment]
Same here im not gettibg the movie thumbnails for new movies and when i search for old movies to save. Exodus is fine for me. I have the Kodi 17.3 verison

**Comment by richd29** [comment]
Yes, seams to be a Specto issue. Thanks for responses everyone. Hopefully, the admins for specto are reading these comments and address the issue on the next update.

**Comment by rkapeller** [comment]
Glad it's not just me. No movie posters. Tried everything.

**Comment by rkapeller** [comment]
What does it take to get someone assigned to the problem? I know they work for free and that is greatly appreciated but this is obviously widespread, and annoying. Thanks.
